format = """
[](#6C0000)\
$python\
$username\
$hostname\
[](bg:#9B1919 fg:#6C0000)\
$directory\
[](fg:#9B1919 bg:#C01C28)\
$git_branch\
$git_status\
[](fg:#C01C28 bg:#D26D52)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$bun\
$dotnet\
$nim\
$rust\
[](fg:#D26D52 bg:#D22D00)\
$docker_context\
[](fg:#D22D00 bg:#D23131)\
$time\
[ ](fg:#D23131)\
"""

command_timeout = 500
scan_timeout = 30
# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#6C0000"
style_root = "bg:#6C0000"
format = '[$user]($style)'

# Show hostname only when connected via SSH, styled identically to username
[hostname]
ssh_only = true
style = "bg:#6C0000"
format = '[@$hostname]($style)'

[directory]
style = "bg:#9B1919"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙󰉋 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙󰉋 "

[c]
symbol = " "
style = "bg:#D26D52"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#D22D00"
format = '[ $symbol $context ]($style) $path'
disabled = true

[elixir]
symbol = " "
style = "bg:#D26D52"
format = '[ $symbol ($version) ]($style)'
disabled = true

[elm]
symbol = " "
style = "bg:#D26D52"
format = '[ $symbol ($version) ]($style)'
disabled = true

[git_branch]
symbol = ""
style = "bg:#C01C28"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#C01C28"
format = '[$all_status$ahead_behind ]($style)'
ignore_submodules = true

[golang]
symbol = " "
style = "bg:#D26D52"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#D26D52"
format = '[ $symbol ($version) ]($style)'
disabled = true

[java]
symbol = " "
style = "bg:#D26D52"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#D26D52"
format = '[ $symbol ($version) ]($style)'
disabled = true

[nodejs]
symbol = ""
style = "bg:#D26D52"
format = '[ $symbol ($version) ]($style)'

[bun]
symbol = ""
style = "bg:#D26D52"
format = '[ $symbol ($version) ]($style)'

[dotnet]
symbol = " "
style = "bg:#D26D52"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#D26D52"
format = '[ $symbol ($version) ]($style)'
disabled = true

[python]
style = "bg:#6C0000"
format = '[(\($virtualenv\) )]($style)'

[rust]
symbol = ""
style = "bg:#D26D52"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R"           # Hour:Minute Format
style = "bg:#D23131"
format = '[ $time ]($style)'
